version: '3.4'

services:
  pythonproject:
    #image: 068182984146.dkr.ecr.eu-central-1.amazonaws.com/brian-test/pythondemo:latest
    # Insert your image full path below
    image: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
